package michaelrunzler.fluiddynamics.generators;

import michaelrunzler.fluiddynamics.block.MaterialEnum;
import michaelrunzler.fluiddynamics.block.ModBlocks;
import michaelrunzler.fluiddynamics.block.OreEnum;
import net.minecraft.data.DataGenerator;
import net.minecraft.world.level.block.Block;

public class FDLootTableProvider extends BaseLootTableProvider
{
    public FDLootTableProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    protected void addTables()
    {
        // Add autogenerated mappings for ores and material blocks
        for(MaterialEnum mat : MaterialEnum.values()){
            String name = "block_" + mat.name().toLowerCase();
            Block block = ModBlocks.registeredBlocks.get(name).get();
            lootTables.put(block, createSimpleTable(name, block));
        }

        for(OreEnum mat : OreEnum.values()){
            String name = "ore_" + mat.name().toLowerCase();
            Block block = ModBlocks.registeredBlocks.get(name).get();
            lootTables.put(block, createSimpleTable(name, block));
        }
    }
}
