package michaelrunzler.fluiddynamics.generators;

import michaelrunzler.fluiddynamics.types.MachineEnum;
import michaelrunzler.fluiddynamics.types.MaterialEnum;
import michaelrunzler.fluiddynamics.block.ModBlocks;
import michaelrunzler.fluiddynamics.types.OreEnum;
import net.minecraft.data.DataGenerator;
import net.minecraft.world.level.block.Block;

public class FDLootTableProvider extends BaseLootTableProvider
{
    public FDLootTableProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    protected void addTables()
    {
        // Add autogenerated mappings for ores, material blocks, and machines
        for(MaterialEnum mat : MaterialEnum.values()){
            String name = "block_" + mat.name().toLowerCase();
            Block block = ModBlocks.registeredBlocks.get(name).get();
            lootTables.put(block, createSimpleTable(name, block));
        }

        for(OreEnum mat : OreEnum.values()){
            String name = "ore_" + mat.name().toLowerCase();
            Block block = ModBlocks.registeredBlocks.get(name).get();
            lootTables.put(block, createSimpleTable(name, block));
        }

        for(MachineEnum mat : MachineEnum.values())
        {
            String name = mat.name().toLowerCase();
            Block block = ModBlocks.registeredBlocks.get(name).get();
            lootTables.put(block, createSimpleTable(name, block));
        }

        //
        // Special non-machine blocks
        //

        lootTables.put(ModBlocks.registeredBlocks.get("machine_frame").get(), createSimpleTable("machine_frame",
                ModBlocks.registeredBlocks.get("machine_frame").get()));
    }
}
