package michaelrunzler.fluiddynamics.generators;

import michaelrunzler.fluiddynamics.recipes.RecipeGenerator;
import michaelrunzler.fluiddynamics.types.MachineEnum;
import michaelrunzler.fluiddynamics.types.MaterialEnum;
import michaelrunzler.fluiddynamics.types.OreEnum;
import net.minecraft.data.DataGenerator;
import net.minecraft.world.level.block.Block;

import java.util.ArrayList;

public class FDLootTableProvider extends BaseLootTableProvider
{
    public static ArrayList<String> nonDefaultLootTableBlocks = new ArrayList<>();

    public FDLootTableProvider(DataGenerator gen) {
        super(gen);
    }

    @Override
    protected void addTables()
    {
        // Add autogenerated mappings for ores, material blocks, and machines
        for(MaterialEnum mat : MaterialEnum.values()){
            String name = "block_" + mat.name().toLowerCase();
            Block block = RecipeGenerator.registryToBlock(name);
            lootTables.put(block, createSimpleTable(name, block));
        }

        for(OreEnum mat : OreEnum.values()){
            String name = "ore_" + mat.name().toLowerCase();
            Block block = RecipeGenerator.registryToBlock(name);
            lootTables.put(block, createSimpleTable(name, block));

            if(mat.hasDeepslateVariant){
                name = "deepslate_ore_" + mat.name().toLowerCase();
                block = RecipeGenerator.registryToBlock(name);
                lootTables.put(block, createSimpleTable(name, block));
            }
        }

        for(MachineEnum mat : MachineEnum.values())
        {
            String name = mat.name().toLowerCase();
            if(nonDefaultLootTableBlocks.contains(name)) continue;

            Block block = RecipeGenerator.registryToBlock(name);
            lootTables.put(block, createSimpleTable(name, block));
        }

        //
        // Special non-machine blocks
        //

        lootTables.put(RecipeGenerator.registryToBlock("machine_frame"), createSimpleTable("machine_frame",
                RecipeGenerator.registryToBlock("machine_frame")));
    }
}
